# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
github: https://github.com/sommerYW

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts
- duoshuo_recent_comments
- links
- weibo
- tag

# Miscellaneous
google_analytics:
favicon: http://s3.sinaimg.cn/middle/0039gsNGzy6SrR1RVT4c2&690
twitter:
google_plus:
fb_admins:
fb_app_id:

# Toc
toc:
  article: false   ## show contents in article.
  aside: true     ## show contents in aside.
# Scroll to top
go_top: true

# duoshuo
duoshuo_shortname: sommeryw

# baidu share
baidushare: true

# blogroll
links:
- name: Sommer
  link: http://sommeryw.github.io

# about me
about_me:
  title: ABOUT ME
  gravatar: a@abc.com
  avatar: 
  texts:
  - I'm Sommer.

# display updated
display_updated: true
